### ISSUE TITLE
文章有点小问题

### ISSUE THREAD

**Issue by xcc3641** [siyehua/StyleTextView#1]
![image](https://cloud.githubusercontent.com/assets/11666634/18496680/69b643f8-7a5a-11e6-9068-327de09c8624.png)
- 底部应该是 `bottom`
- 项目里的 .idea 一般不用上传

**Comment by siyehua** [comment]
@xcc3641 谢三弟,我这辈子就没说过一个谢字.感谢指正

图片来源于网络,确实没注意到bottom拼写错误问题

.idea目录被上传上来是因为.gitignore是IDE自动生成的,没有控制其上传

再次感谢指正
